# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import neural_nets_pb2 as neural__nets__pb2


class LayerDataExchangeStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendInput = channel.unary_unary(
        '/nn.LayerDataExchange/SendInput',
        request_serializer=neural__nets__pb2.ForwardMsg.SerializeToString,
        response_deserializer=neural__nets__pb2.PlainResponse.FromString,
        )
    self.BackwardDelta = channel.unary_unary(
        '/nn.LayerDataExchange/BackwardDelta',
        request_serializer=neural__nets__pb2.BackwardMsg.SerializeToString,
        response_deserializer=neural__nets__pb2.PlainResponse.FromString,
        )


class LayerDataExchangeServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendInput(self, request, context):
    """get layer inputs
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BackwardDelta(self, request, context):
    """get backward deltas
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_LayerDataExchangeServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendInput': grpc.unary_unary_rpc_method_handler(
          servicer.SendInput,
          request_deserializer=neural__nets__pb2.ForwardMsg.FromString,
          response_serializer=neural__nets__pb2.PlainResponse.SerializeToString,
      ),
      'BackwardDelta': grpc.unary_unary_rpc_method_handler(
          servicer.BackwardDelta,
          request_deserializer=neural__nets__pb2.BackwardMsg.FromString,
          response_serializer=neural__nets__pb2.PlainResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'nn.LayerDataExchange', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
